name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  UV_SYSTEM_PYTHON: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install system deps (Linux)
        uses: awalsh128/cache-apt-pkgs-action@v1.6.0
        with:
          packages: libcairo2-dev libgirepository1.0-dev
          version: 1.0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: .python-version
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "latest"
          enable-cache: true
      - name: Check uv.lock is up to date
        run: |
          make python/lock-check
      - name: Install dependencies
        run: |
          make python/install
      - name: Run tests
        run: |
          make python/unit-tests